# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2-pre-2
loader_version=0.19.2

# Mod Properties
mod_version=1.1.10
maven_group=me.chillywilly
archives_base_name=camera-plugin-helper

# Mod Dependencies
fabric_version=0.150.1+26.2
# https://modrinth.com/mod/fabric-language-kotlin/versions
fabric_language_kotlin_version=1.13.10+kotlin.2.3.20


# Other Dependencies
# https://central.sonatype.com/artifact/com.squareup.okhttp3/okhttp/5.3.0/versions
okhttp_version=5.3.2
# https://central.sonatype.com/artifact/com.squareup.okio/okio/3.16.2
okio_version=3.17.0